### ISSUE TITLE
Add items to the "press" page

### ISSUE THREAD

**Issue by lukefretwell** [distributedteams/website#12]
https://distributedteamsbook.com/press/

**Comment by joduinn** [comment]
https://github.com/distributedteams/website/blob/master/_data/press.yml

**Comment by joduinn** [comment]
Good selection there now. 

@lukefretwell : right now, its all still one list. Would you like these organized as  articles vs podcasts vs video interviews ?

**Comment by joduinn** [comment]
Also, wasnt sure what to do with this: https://www.infoq.com/articles/book-review-distributed-teams/

It was a written interview, specifically about the 1st edition of the book. Include or skip?

**Comment by joduinn** [comment]
(1) Added articles to the press.yml file
(2) now have the press.html page listing four categories. 


As new articles come up, all we need to do is add to the press.yml, and the rest works automatically! 

All done here.
