### ISSUE TITLE
Setup google Analytics

### ISSUE THREAD

**Issue by joduinn** [distributedteams/website#2]

**Comment by lukefretwell** [comment]
@joduinn just add the UA code here:

https://github.com/distributedteams/website/blob/master/_includes/analytics.html#L15

**Comment by joduinn** [comment]
Change merged. Will leave this open until tomorrow after I verify that data is showing up correctly in google analytics

**Comment by joduinn** [comment]
Urgh. So far nothing showing up on GA, even after I hit the website from a few different browsers, including private browser mode. Will investigate tomorrow.

**Comment by joduinn** [comment]
Now working (needed to use old UA- style ID instead of the new style G- style ID).
